apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sonarqube.fullname" . }}-ssl
data:
  client-cert.pem: {{ .Values.ssl.clientcert | quote }}
  client-key.pk8: {{ .Values.ssl.clientkey | quote }}
  server-ca.pem: {{ .Values.ssl.serverca | quote }}

